AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  ddbTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: access
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lambda-artifacts-6c65e1d0551810ea/f8282bfef77b1de807b65613c21032c7
      Handler: example.Handler
      Runtime: java8
      Description: Java function
      Environment:
        Variables:
          DDB_TABLE:
            Ref: ddbTable
      MemorySize: 512
      Timeout: 10
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ddbTable
      Tracing: Active
